language: php

php:
  - 5.3
  - 5.5

env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1
    - WP_VERSION=3.6.1 WP_MULTISITE=0
    - WP_VERSION=3.6.1 WP_MULTISITE=1


script: "vendor/bin/phpunit Tests"
